version: '3'

services:
  apptest01_blue:
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=file-logging
    build:
        context: .
        dockerfile: ./DockerfileApp1

    volumes:
      - ./logs/spring-boot/:/usr/log/
    networks:
      - apps_frontend

  apptest_blue:
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=file-logging
    build:
        context: .
        dockerfile: ./DockerfileApp2

    volumes:
      - ./logs/spring-boot2/:/usr/log/
    networks:
      - apps_frontend

networks:
  apps_frontend:
    external: true
    
 
