server: 
  port: 8080
  
management:
  security:
     enabled: false
  endpoint:
    health:
     show-details: "ALWAYS"
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
debug: true

logging:
  path: /usr/log/

     
